services:
  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "lw_db"
      POSTGRES_USER: "dmadonna"
      POSTGRES_PASSWORD: "1425"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
