services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "2525:2525"
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      PORT: 2525
#      DB_HOST: 127.0.0.1
#      INSTANCE_UNIX_SOCKET:  127.0.0.1:2525
#      DB_USER: "dmadonna"
#      DB_PASSWORD: "1425"
#      RDB_ADDR: "localhost:6379"
#      RDB_USER: "default"
#      RDB_PASSWORD: ""
#      RDB_NO: 0
#      AUTH0_DOMAIN: "dev-dtwzinh2v8hlmwqm.us.auth0.com"
#      AUTH0_AUDIENCE: "http://localhost:2525/go_services"
#      STORAGE_BUCKET: "lw-user-images"

  postgres:
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "lw_db"
      POSTGRES_USER: "dmadonna"
      POSTGRES_PASSWORD: "1425"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - 6379:6379




